### ISSUE TITLE
코스모스 베이직 모듈 작업 분담하기

### ISSUE THREAD

**Issue by woon999** [Ludium-Official/road-to-dubai#1]
## 작업 파트 범위 (그냥 임의로 나눔)
- 블록체인 기초
- 코스모스 베이직 & 앱체인 생태계   
- 컨센서스 (CometBFT, 텐더민트)
- cosmos-sdk 온보딩 실습 (go, rpc, etc ...)

https://ludium.world/announcement/7b3ccad7-fc8e-4de7-aea8-cfdfac0bbc0b/549322a6-fa95-4952-9f8b-a72fd62eacdf

**Comment by jeongseup** [comment]
내용 봤는데 제가 컨센서스 파트는 딱히 안 건드렸거든요 일단 앱체인이란 왜 생겨났고 어떤구조인지 말과 자료를 위주로 설명하고 실습은 좀 더 구상해볼게요! 

컨센서스 파트 하실거면, 담당해주시면 감사하겠습니다.. (어려워서 ㅠ)

**Comment by woon999** [comment]
> 용 봤는데 제가 컨센서스 파트는 딱히 안 건드렸거든요 일단 앱체인이란 왜 생겨났고 어떤구조인지 말과 자료를 위주로 설명하고 실습은 좀 더 구상해볼게요!
> 
> 컨센서스 파트 하실거면, 담당해주시면 감사하겠습니다.. (어려워서 ㅠ)

넵 좋습니다~!

**Comment by loosie** [comment]
작업 파트 담당 이렇게 나눠서 진행하는 거 괜찮을까요? 
- 블록체인 베이직 & 컨센서스 (CometBFT, 텐더민트 포함) - @loosie 
- 코스모스 베이직 & 앱체인 생태계   @Jeongseup

**Comment by woon999** [comment]
@Jeongseup  우선 코스모스 베이직 아티클 부분 정습님이 주도적으로 맡아서 해주시고 저는 그 부분에서 컨선서스 파트를 하는 방향으로 가는 것으로 알고 이슈 닫겠습니다~ 그리고 golang 기초, 실습 부분은 컨센서스 파트에 묶어서 해볼 수도 있을 것 같아요 (루디움 디코 채널에 올린 내용)

**Comment by jeongseup** [comment]
우선 그럼 어플리케이션 파트에 어제 작성한 내용은 금일 저녁에 마무리 짓고 PR 올려둘게요
