### ISSUE TITLE
cosmos sdk step2 제작

### ISSUE THREAD

**Issue by woon999** [Ludium-Official/road-to-dubai#6]
step1에서는 cosmos-sdk 로 만든 simapp에 대한 이해과 전반적인 이해를 마무리하고 step2에서는 조금 더 코스모스 인터체인에 대한 블록체인 지식을 습득한다. 
> cosmos sdk docs 기반으로 작성할 예정 
1. transcation life cycle [아티클 + 코드 기반]
   1. 트랜잭션
   2. Mempool
   3. 트랜잭션 라이프 사이클
      1. 트랜잭션 생성
      2. 트랜잭션 Broadcasting
      3. Mempool에 추가하기
      4. Block에 포함하기
      5. 상태 변경하기
2. account 
   1. 공개 키 암호화
   2. Account
   3. Signature
   4. Address
   5. Keyring
4. gas fee
   1. Gas fee란
   2. Gas Meter
   3. AnteHandler
5. store and keepers
   1. Store
   2. KVStore
   3. KVStore Wrapper
   4. Multistore
   5. Keeper
6. rpc & encoding & query 
   1. rpc basic
   2. encoding 
   3. grpc & rest & cometbft rpc
   4. query

**Comment by woon999** [comment]
1. transcation - https://github.com/Ludium-Official/road-to-dubai/pull/8
2. protobuf랑 같이 엮어서 추후 업로드 
3. accounts - https://github.com/Ludium-Official/road-to-dubai/pull/9
4. gas fees - https://github.com/Ludium-Official/road-to-dubai/pull/10
5. Store and Keepers https://github.com/Ludium-Official/road-to-dubai/pull/11 (app chain으로 넣을 수 있으나 일단 여기다 추가)

**Comment by woon999** [comment]
as-is
```
2. query life cycle [아티클 + 코드 기반]
    1. 쿼리 생성(CLI, REST, gRPC)
    2. 쿼리 핸들링 
    3. 쿼리 응답 
```

to-be
```
2. rpc, encoding, query
```   


2. rpc, encoding, query - https://github.com/Ludium-Official/road-to-dubai/pull/18

**Comment by jeongseup** [comment]
#3 closed issue for step2
